### ISSUE TITLE
 Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by wanglong167** [opbeat/opbeat-node#66] opened 2016-08-06 16:32 UTC
```
logging error with Opbeat: { uuid: '7ddfd240-0f20-49a1-9355-f9f8ee6c4b94' }
TypeError: Cannot read property 'apply' of undefined
    at Command.wrappedCallback (E:\www_node\vscene\vscene-h5\node_modules\opbeat\lib\instrumentation\modules\redis.js:36:20)
    at Command.instrumented [as callback] (E:\www_node\vscene\vscene-h5\node_modules\opbeat\lib\instrumentation\index.js:112:27)
    at normal_reply (E:\www_node\vscene\vscene-h5\node_modules\redis\index.js:714:21)
    at RedisClient.return_reply (E:\www_node\vscene\vscene-h5\node_modules\redis\index.js:816:9)
    at JavascriptRedisParser.Parser.returnReply (E:\www_node\vscene\vscene-h5\node_modules\redis\index.js:188:18)
    at JavascriptRedisParser.execute (E:\www_node\vscene\vscene-h5\node_modules\redis\node_modules\redis-parser\lib\parser.js:413:12)
    at Socket.<anonymous> (E:\www_node\vscene\vscene-h5\node_modules\redis\index.js:267:27)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
    at TCP.instrumented [as onread] (E:\www_node\vscene\vscene-h5\node_modules\opbeat\lib\instrumentation\index.js:112:27)
```

**Comment by roncohen** [comment] 2016-08-08 10:18
Thanks for reporting this issue @wanglong167. It seems to be a duplicate of #64. I've submitted #65 to fix it. Can you try it out and tell me if that solves your problem?

**Comment by roncohen** [comment] 2016-08-08 19:23
Closing this as a duplicate. Feel free to re-open if it turns out not to be the case.

**Closed by roncohen** 2016-08-08 19:23 UTC
